#!/usr/bin/env sh

# args:
#     1: path to test-folder
#     2: server url
#     3: csv file

command -v jq > /dev/null || { printf "Install jq please"; exit 1; }

printf "Distance,Id,Image\\n" > "$3"
for img in $1/*; do
  response=$( curl -s -X POST -F "file=@$img" "$2" )
  count=$( printf "%s" "$response" | jq '.count' )
  if [ "$count" -eq 1 ]; then
    dist=$( printf "%s" "$response" | jq '.faces[0].dist' )
    id=$( printf "%s" "$response" | jq '.faces[0].id' )
    image=$( printf "%s" "$img" | rev | cut -d "/" -f 1 | rev )
    printf "%s,%s,%s\\n" "$dist" "$id" "$image" >> "$3"
  fi
done
