#!/usr/bin/env sh

# args:
#     1: path to test-folder
#     2: server url
#     3: csv file

printf "Distance,Id,Image\\n" > "$3"

for img in $1/*; do
  response=$( curl -s -X POST -F "file=@$img" "$2" \
	  | tr ',' '\n' \
	  | sed "s/{//g;s/}//g;s/\[//g;s/\]//g;s/faces://g" \
  )
  flag=0
  printf "%s" "$response" | grep "count: 1" > /dev/null 2&>1 || flag=1
  [ "$flag" -eq 0 ] && {
    printf "%s" "$response" | tail -n +2 | cut -d ":" -f 2 | tr '\n' ',' >> "$3"
    printf "%s\\n" "$img" >> "$3";
  }
done
