#!/usr/bin/env sh

# args:
#     1: link to img page: https://www.gettyimages.it/editorial-images
#     2: output file
curl -s "$1" \
	| grep -o -P "https:\/\/media.gettyimages.com\/photos\/[a-zA-z-0-9=&;]{2,}" \
	| sort \
	| uniq > "$2"
