version: '3'
services:
        reverseproxy:
                image: reverseproxy:latest
                container_name: reverseproxy
                ports:
                        - 22:22
                        - 80:80
                        - 443:443
                        - 26656:26656
                        - 26657:26657
                        - 9984:9984
                        - 9985:9985
                        - 2812:2812
                        - 27017:27017
                restart: unless-stopped
        node1:
                image: mybigchaindb:latest
                depends_on:
                        - reverseproxy
                container_name: node1
                restart: unless-stopped
        node2:
                image: mybigchaindb:latest
                container_name: node2
                restart: unless-stopped
        node3:
                image: mybigchaindb:latest
                container_name: node3
                restart: unless-stopped
        node4:
                image: mybigchaindb:latest
                container_name: node4
                restart: unless-stopped
